baseURL: https://humberto.io/
DefaultContentLanguage: en
title: Humberto Rocha
theme: colordrop
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

taxonomies:
  tag: tags

menu:
  footer:
    - identifier: mastodon
      name: mastodon
      url: https://takahe.humberto.io/@humrochagf@humberto.io
      weight: 1
    - identifier: github
      name: github
      url: https://github.com/humrochagf/
      weight: 2
    - identifier: curriculum
      name: curriculum
      url: curriculum/
      weight: 3
    - identifier: rss
      name: rss
      weight: 4

params:
  title: Humberto Rocha
  description: A blog to put into words a portion of my knowledge about coding, technology, and much more. I hope you find here something that can help you as it helped me before 😊
  images:
    - img/me.png
  themeColor: "#000000"
  themeInverseColor: "#ffffff"
  siteLogo: img/me.png

  tracking:
    domain: https://u.humberto.io
    websiteId: "0236bfe6-0441-47dd-a266-4054efab6a70"

  author:
    name: Humberto Rocha
    job: Developer
    gender: male
    image: img/me.png
    github: humrochagf
    linkedin: humrochagf

  license:
    name: Attribuition-ShareAlike
    type: by-sa
    version: "4.0"
    locale: en
    size: 88x31

languages:
  en:
    languageName: English
    weight: 1
  pt-br:
    languageName: Português Brasileiro
    weight: 2
    params:
      description: Um blog onde eu coloco em palavras um pouco do meu conhecimento sobre programação, tecnologia e muito mais. Espero que você encontre aqui algo que possa lhe ajudar, assim como esse conhecimento já me ajudou um dia 😊
      license:
        name: Atribuição-CompartilhaIgual
        type: by-sa
        version: "4.0"
        locale: pt_BR
        size: 88x31
  fr:
    languageName: Français
    weight: 3
    params:
      description: Un blog ou je mets en mots une partie de mon savoir à propos de la programmation, de la technologie et plus encore. J'espère que vous trouvez des choses qui pourront vous aider comme ça m'a déjà aidé 😊
      license:
        name: Attribution - Partage dans les Mêmes Conditions
        type: by-sa
        version: "4.0"
        locale: fr
        size: 88x31
